name: NPM Release

on:
  push:
    branches:
      - main
    paths:
      - create-disclosure-bot/**

jobs:
  npm-release:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 17
          registry-url: https://registry.npmjs.org/

      - run: npm publish
        working-directory: create-disclosure-bot
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
