name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 17

      - run: npm ci

      - run: node ./scripts/ci-build.js

      - run: npm run build

      - name: Exclude plugin folder then recreate it
        run: |
          rm -rf plugins
          mkdir plugins

      - name: Create release archive
        run: tar -cvzf disclosure-bot.tar.gz package.json dist LICENSE plugins scripts tsconfig.base.json

      - name: Create checksum.txt
        run: |
          SUM=`sha256sum disclosure-bot.tar.gz`
          echo $SUM > checksum.txt

      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: |
            Full Changelog: ['CHANGELOG.md'](https://github.com/oadpoaw/disclosure-bot/blob/main/CHANGELOG.md)
          files: |
            disclosure-bot.tar.gz
            checksum.txt

  docs:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - run: npm ci
      - run: node ./scripts/ci-build.js
      - run: npm run docs
      - run: rm -rf src package.json package-lock.json .github tsconfig.json create-disclosure-bot plugins scripts .vscode SECURITY.md CHANGELOG.md tsconfig.base.json

      - run: cp -r docs/** .

      - run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "docs"
          git push origin HEAD:gh-pages --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
